france_champignon:
  data: 
    gas_cons:
      dirpath: 'data/france_champignon/' # filename = data_bonduelle.csv
      frequency: 'h'
      timezone: 'CET' # ou CEST, je ne sais pas, pas 'Europe/Paris'
      timestamp_col: 'date/heure 2024'
      timestamp_format: '%d/%m/%Y %H:%M'
      comment_on_hour_change: 'Not relevant for this timezone'

inariz:
  data:
    steam_prod: 
      dirpath: 'data/inariz/raw/'
      skiprows: 4
      usecols: ["Horodatage","Valeur","Unité"]
      timezone: 'Europe/Paris'
      timestamp_col: 'Horodatage'
      timestamp_format: '%Y-%m-%d %H:%M:%S.%f'
      comment_on_hour_change: 'March: visible, one day with 23 hours. October: visible in boiler-box with 25 hours, the last value before the hour change is persisted for an hour.'
  prix_seuil_euro_mwh: [58, 60, 70]
  puissance_chaudiere_elec_mw: 2
  capacite_min_gaz_kwhth: 2500 #todo vérifier : dit que son output est toujours de minimum 2.5 kwh thermiques de vapeur, ou bien que son input est toujours de minimum 2.5 kwh de gaz ? Dans les captures d'écran où je trouve ça, je vois bien 0.25 MWh th
  # serait alors plutôt une production_min_chaudiere_gaz_kwhth !

tarkett:
  data:
    gas_cons:
      dirpath: 'data/tarkett/raw/' # filename = Données de Consommation gaz 2025
      timezone: 'Europe/Paris'
      timestamp_col: 'Valeur mesurée le'
      timestamp_format: '%d/%m/%Y %H:%M:%S'
      comment_on_hour_change: 'Invisible, in data gaps'



models:
  LinearRegression:
    params:
      fit_intercept: False
