france_champignon:
  data: 
    path: 'data\france_champignon\data_bonduelle.csv'
    frequency: "h"
    timezone: 'Europe/Paris'

inariz:
  data: 
    path: 'data\inariz\raw\Graphique_20260121150818.csv'
    skiprows: 4
    usecols: ["Horodatage","Valeur","Unité"]
    timezone: 'Europe/Paris'

tarkett:
  data:
    path: 'D:\Cascadya\Cascadya - Documents\08. COMPTE CLIENT\Tarkett_Sedan\2. Données sous NDA\Données de Consommation gaz 2025'
    timezone: 'Europe/Paris'



models:
  LinearRegression:
    params:
      fit_intercept: False