---
- name: Validate remote unlock on Cascadya IPC
  hosts: all
  become: true
  gather_facts: true

  vars:
    remote_unlock_enable: true
    remote_unlock_phase: validate

  roles:
    - role: remote-unlock
