---
- name: Install WireGuard
  ansible.builtin.apt:
    name:
      - wireguard
      - resolvconf
    state: present

- name: Optionally enable IP forwarding for WireGuard routing use cases
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  when: network_enable_ip_forward | bool

- name: Deploy WireGuard Config
  ansible.builtin.copy:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
    owner: root
    group: root
  notify: Restart WireGuard

- name: Enable WireGuard Service
  ansible.builtin.systemd_service:
    name: wg-quick@wg0
    enabled: true
    state: started
