[broker]
broker01 ansible_host=51.15.64.139 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[broker:vars]
ansible_python_interpreter=/usr/bin/python3
vault_role=broker

[edge]
edge-local ansible_connection=local

[edge:vars]
ansible_become=true
ansible_become_method=sudo
vault_role=edge