global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

accessLog:
  filePath: /var/log/traefik/access.log

api:
  dashboard: false

entryPoints:
  websecure:
    address: ":443"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
