[Interface]
Address = 10.8.0.1/24
ListenPort = 51820
PrivateKey = 4EWSXdA2CB1Wl7GEzF88Ux6zcbZyvCP0pnbgaql4K3w=

# NAT + routage pour accès aux sous-réseaux Scaleway
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -A FORWARD -o wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o ens2 -j MASQUERADE

PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o ens2 -j MASQUERADE

[Peer]
# Client Daniel
PublicKey = CfIJb+JE+XhHPv56yoO8vOY5N6vdfvtVkncWLjh2SFs=
AllowedIPs = 10.8.0.2/32
[Peer]
# Client Mahmoud
PublicKey = hWUK1fbb1hhxbQuxG3ADRdMufLNNIid6ZHQ7E6C4XVo=
AllowedIPs = 10.8.0.3/32
[Peer]
# Client Loris
PublicKey = +y8MTJ6zkfhc6t3GT7xOF8lNmevOVrhnHEE8Pd9tcHw=
AllowedIPs = 10.8.0.4/32
[Peer]
# Routeur 5G Teltonika (RUTX50)
PublicKey = MEfwzbh2YrAd7bQ6ZxOD2fHcsq4+KyrQMzH9hiwd5m4=
AllowedIPs = 10.8.0.5/32, 192.168.10.0/24, 192.168.50.0/24
[Peer]
# Client Luc
PublicKey = WdKmWbQrJcXUKfKN/vc1vxXR7mUgdrrgoq24sfikCjY=
AllowedIPs = 10.8.0.6/32
[Peer]
# Client Dominique
PublicKey = Sighb7IGqCs6Vh7zPe+1dZ8eIFU4hccc8NjXTkauYTQ=
AllowedIPs = 10.8.0.7/32